#!/bin/bash
set -eou pipefail

rm -rf frequency
rm -rf tf-idf
mkdir frequency
mkdir tf-idf


# Calculate each term's inverse document frequency
TOTAL_DOCUMENTS=$(ls -1 counts | wc -l)
cat counts/*.md | cut -f1 -d' ' | sort | uniq -c | awk '{print $2, $1}' >  document.counts
awk "{print \$1, log($TOTAL_DOCUMENTS/\$2)}" document.counts > term.idf

# Calculate tf-idf for each term in each file in counts/
for COUNTFILE in counts/*
do
	BN=$(basename $COUNTFILE)
	TOTAL_TERMS=$(cut -f2 -d' ' $COUNTFILE | awk '{sum += $1} END {print sum})
	awk "{print \$1, \$2/$TOTAL_TERMS}" $COUNTFILE > frequency/$BN
	join frequency/$BN term.idf |
		awk '{printf "%s\t%f\n", $1, $2 * $3}' |
		sort -k2.1nr > tf-idf/$BN
done
